Create jernej_urankar.rst
DragonSprint/dragonsprint.com pull request #26
Opened 2016-12-06 10:14 UTC by jerneju

2016-12-06 10:16 UTC, karantan commented on content/jernej_urankar.rst
> +:image: /images/jernej_urankar.jpg
You forgot to add image.

2016-12-06 11:42 UTC, JanLikar requested changes
Add the image

2016-12-06 13:52 UTC, zupo commented
@jerneju: you forgot to commit the image file

2016-12-08 12:51 UTC, JanLikar commented
Replaced by #28

2016-12-08 12:51 UTC, closed without merging